### ISSUE TITLE
proxy support would be nice

### ISSUE THREAD

**Issue by andreasschulze** [Snawoot/postfix-mta-sts-resolver#1]
Hello,

currently the code try to connect a remote https://mta-sts.$domain only direct.
There seem to be no support for a proxy implemented while aiohttp [do provide support](https://docs.aiohttp.org/en/stable/client_advanced.html#proxy-support)

what is the suggested way to tun the resolver behind a proxy?

Andreas

**Comment by Snawoot** [comment]
I think I should improve HTTP requests code. As I'll complete it, app will not create unnecessary connection pool for each request and will respect proxy settings from system environment variables.

**Comment by Snawoot** [comment]
Added in release 0.2.2. Now resolver respects environment variables HTTPS_PROXY and NETRC.

**Comment by andreasschulze** [comment]
I just tested the new version and can confirm HTTPS_PROXY works like expected.
Awesome! Thanks!
