### ISSUE TITLE
Support unix sockets for daemon

### ISSUE THREAD

**Issue by clarfon** [Snawoot/postfix-mta-sts-resolver#39]
Right now, the config supports `host` and `port` options for the responder. It makes sense to also offer a `path` option for unix sockets. This wouldn't be too hard, as the only thing that really needs to be changed is the `create_custom_socket` function in `utils.py` and its call in responder.py`.

**Comment by Snawoot** [comment]
Merged via #40, released to PyPI via v0.6.0 (639b2ab).

**Comment by clarfon** [comment]
Thank you for implementing this so quickly!
