### ISSUE TITLE
Allow configuring the unix socket permissions

### ISSUE THREAD

**Issue by bjoe2k4** [Snawoot/postfix-mta-sts-resolver#45]
**Is your feature request related to a problem? Please describe.**

By default the socket is created with the permissions `0o755` on my system and postfix won't be able to connect since it runs as a different user. Putting the postfix user in the mta-sts group won't help either.

**Describe the solution you'd like**

I'd be nice to be able to configure the permissions via the config file.

**Describe alternatives you've considered**

For now I've added `ExecStartPost=/usr/bin/chmod 666 socketfd` to the systemd unit file. This works, but you have to configure the socket twice, once in the config, once in the systemd file.

**Comment by Snawoot** [comment]
Released in `v0.7.0`
