### ISSUE TITLE
Policies for Smarthosts

### ISSUE THREAD

**Issue by galme** [Snawoot/postfix-mta-sts-resolver#49]
**Describe the bug**
When a client is configured to use a smarthost/relay/relayhost for its mail delivery, the policy lookup (and validation) is not initiated.

**To Reproduce**
1. configure postfix to use a relay (example config line in main.cf: `relayhost = [myrelayhost.example.com]:123`)
2. attempt to send a valid email to someone/somewhere
3. _mail.log_ says _Trusted TLS connection established_ (but not Verified as it should be) and there are no logs in _mta-sts.log_ to signify a lookup on a domain for policies.

**Expected behavior**
The proposed MTA-STS standard (RFC 8461) section _3.4.  Policy Selection for Smart Hosts and Subdomainsin section_ ([link](https://tools.ietf.org/html/rfc8461#section-3.4)) states:
> When sending mail via a "smart host" -- an administratively configured intermediate SMTP relay, which is different from the message recipient's server as determined from DNS -- compliant senders MUST treat the smart host domain as the Policy Domain for the purposes of policy discovery and application.

My understanding is that there should be a policy lookup and validation for the `example.com` domain in this case.

Note: had the configuration been without the brackets (like `relayhost = myrelayhost.example.com:123`), I would expect for `myrelayhost.example.com` to be looked up and validated (since _myrelayhost_ isn't really a host then but rather a _subdomain_ due to the allowed MX lookups from the absence of []).

**Output listings**
_mta-sts.log:_
STS: Enq request: b'postfix [myrelayhost.example.com]:123'

**Environment (please complete the following information):**
 - OS: Linux
 - Distro: Ubuntu 
 - Distro version: 18.04.3 LTS
 - Python version: 3.6.9

**Additional context**
I found the short-circuit code responsible for this behaviour here: [link](https://github.com/Snawoot/postfix-mta-sts-resolver/blob/af9a7e2de99e0801649509be0f2177f333e025e0/postfix_mta_sts_resolver/responder.py#L166-L169). If I hack around this (extract the host's domain), the TLS connection shows as verified and the lookups & validations are done as expected.

P.S. Thank you for the work put into this project!

**Comment by Snawoot** [comment]
Hello! Thanks!

> My understanding is that there should be a policy lookup and validation for the example.com domain in this case.

It seems in smart host case domain policy should be looked up literally for `myrelayhost.example.com`. RFC says nothing about extraction of subdomain parent domain and we can't assume MX policy for example.com has something to do with STS policy of `myrelayhost.example.com` relay. Also it is imperative for correct validation to have `myrelayhost.example.com` listed in `mx` list of STS policy for `myrelayhost.example.com`.

> If I hack around this (extract the host's domain), the TLS connection shows as verified and the lookups & validations are done as expected.

Could you please put together a Pull Request with changes? Basically all we need to do here is:
1. Cut brackets and port, extract domain part
2. Skip requests which contain IP address instead of domain name because we cant infer MTA-STS policy domain for them.
3. Optionally add few new testcases with brackets in request.

You can reliably distinguish IP address from domain name with function like this:

```python
def is_ipaddr(addr):
    try:
        socket.getaddrinfo(addr, None, flags=socket.AI_NUMERICHOST)
        return True
    except socket.gaierror:
        return False
```

**Comment by galme** [comment]
> It seems in smart host case domain policy should be looked up literally for myrelayhost.example.com. RFC says nothing about extraction of subdomain parent domain and we can't assume MX policy for example.com has something to do with STS policy of myrelayhost.example.com relay. Also it is imperative for correct validation to have myrelayhost.example.com listed in mx list of STS policy for myrelayhost.example.com.

I was basing it more on Postfix's special [] bracket notation rather than the RFC. But I agree that the relation between [hostname] and its parent domain can be a too big of an inference/assumption.

Side note here. After a brief check, I haven't found any email providers to support MTA-STS on their relays yet. Those that do have MTA-STS configured, only seem to have it for their inbound/end-recipient servers only. I'd love to see it being adopted more.

> Could you please put together a Pull Request with changes?
Sure, I'll code it out.
