### ISSUE TITLE
Notice for Postfix 3.4+ users

### ISSUE THREAD

**Issue by Snawoot** [Snawoot/postfix-mta-sts-resolver#65]
There is a [bug](https://www.mail-archive.com/postfix-users@postfix.org/msg87050.html) in Postfix 3.4+ which makes Postfix unable to load the key+cert+chain.

Make sure you have `smtpd_tls_eecdh_grade` in it's default value `auto` or you have Postfix version which contains fix for this bug.

**Comment by polarathene** [comment]
> Postfix version which contains fix for this bug

Seems from the linked discussion that it got patched: https://www.mail-archive.com/postfix-users@postfix.org/msg87364.html

If I understand that correctly, 3.4 + 3.5 + 3.6 all received a patch update for it. Anything newer than 3.6 should definitely have the fix.

**Comment by Snawoot** [comment]
Thank you!
