### ISSUE TITLE
Move to aioredis v2

### ISSUE THREAD

**Issue by bjoe2k4** [Snawoot/postfix-mta-sts-resolver#77]
**Is your feature request related to a problem? Please describe.**
From the docs of v2: `As of December, 2019, this library had been abandoned`

v2 started hitting repos of rolling release distros (e.g. Archlinux) a while ago. I'd prefer to install that instead of an outdated and unmaintained version from two years ago which conflicts with the current version unless docker or pyenv is used.

**Describe the solution you'd like**
make a clear brake and adapt to new aioredis API

**Describe alternatives you've considered**
support both aioredis versions

**Additional context**
I've managed to do the necessary changes in `redis_cache.py`. Please let me what solution is preferred so that I may prepare a pull request.

**Comment by Snawoot** [comment]
Hello,

Thanks for reaching out! It's better to drop old aioredis version. Those who need older version have following options:

* use older version of pmsr
* drop old storage implementation into pmsr package. or implement whatever they like, it's fairly small interface to implement.
